
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MD RAKIBUL ISLAM
 */
public class CustomerOffer extends javax.swing.JFrame {

    public ImageIcon icn;
    Connection con = null;
    String mnname;
    int prprice;

    String menutype = "SELECT * FROM `offer`";

    /**
     * Creates new form SetImageBackground
     */
    public CustomerOffer() {
        con = DB.dbconnect();
//        this.setUndecorated(true);
//        this.setAlwaysOnTop(true);
        this.setTitle("Restaurant RRMS");

        icn = new ImageIcon(getClass().getResource("/Images/icn.png"));
        this.setIconImage(icn.getImage());
        this.setResizable(false);
        initComponents();
        show_menu();
        show_order();
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        bg.setBackground(new Color(0, 0, 0, 200));
        menubar.setBackground(new Color(0, 0, 0, 200));
        orderpanal.setBackground(new Color(0, 0, 0, 150));
        Login lg = new Login();
        uname.setText(lg.user);
        urestu.setText(lg.restu);
        cust.setText("(" + lg.ob + ")");
    }

    public ArrayList<Menus> menuList() {
        ArrayList<Menus> menuList = new ArrayList<>();
        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant", "root", "");
//            System.out.println("Connecteced !!");
            String queryl = menutype;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(queryl);
            Menus menu;
            while (rs.next()) {
                menu = new Menus(rs.getString("Menu_ID"), rs.getString("Name"), rs.getString("Price"), rs.getString("Offer"));
                menuList.add(menu);

                String totalcrg = "SELECT SUM(Price) FROM `order`;";
                Statement st1 = con.createStatement();
                ResultSet rs1 = st1.executeQuery(totalcrg);
                while (rs1.next()) {
                    String prc = rs1.getString("SUM(Price)");
                    ttl.setText(prc + " TK.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return menuList;
    }

    public void show_menu() {
        ArrayList<Menus> list = menuList();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getMenuID();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getPrice();
            row[3] = list.get(i).getType();
            model.addRow(row);
        }
    }

    public ArrayList<orders> orderList() {
        ArrayList<orders> orderList = new ArrayList<>();
        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant", "root", "");
//            System.out.println("Connecteced !!");
//            String queryl = menutype;
            String queryl = "SELECT * FROM `order`";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(queryl);
            orders order;
            while (rs.next()) {
                order = new orders(rs.getString("name"), rs.getString("quantity"), rs.getString("price"));
                orderList.add(order);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return orderList;
    }

    public void show_order() {
        ArrayList<orders> list = orderList();
        DefaultTableModel model = (DefaultTableModel) ordertable.getModel();
        Object[] row = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getName();
            row[1] = list.get(i).getQuantity();
            row[2] = list.get(i).getPrice();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menubar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        cust = new javax.swing.JLabel();
        urestu = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        menupanal1 = new javax.swing.JPanel();
        menutable1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        oname = new javax.swing.JLabel();
        oprice = new javax.swing.JLabel();
        fprice = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        next = new javax.swing.JToggleButton();
        orderpanal = new javax.swing.JPanel();
        menutable = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        add = new javax.swing.JToggleButton();
        delet = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        placement = new javax.swing.JComboBox<>();
        qnt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ttl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RAKIB'S RESTAURANT MANAGEMENT SYSTEM");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Offer");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("| Log Out");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icn36.png"))); // NOI18N

        javax.swing.GroupLayout menubarLayout = new javax.swing.GroupLayout(menubar);
        menubar.setLayout(menubarLayout);
        menubarLayout.setHorizontalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        menubarLayout.setVerticalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(menubarLayout.createSequentialGroup()
                        .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 255, 153));
        jLabel20.setText("Welcome !");
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 438, -1, -1));

        uname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uname.setForeground(new java.awt.Color(102, 255, 255));
        uname.setText("Mr. User");
        bg.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 461, -1, -1));

        cust.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cust.setForeground(new java.awt.Color(102, 255, 255));
        cust.setText("(Manager)");
        bg.add(cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 484, -1, 15));

        urestu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        urestu.setForeground(new java.awt.Color(102, 255, 255));
        urestu.setText("ABC RESTAURANT");
        bg.add(urestu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 505, -1, 15));

        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 419, 250, 13));

        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 250, 12));

        jSeparator5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 210, 260, 12));

        jSeparator6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 240, 12));

        jSeparator7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 350, 260, 12));

        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 260, 12));

        jSeparator8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 10));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 51));
        jLabel25.setText("Order Now");
        bg.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("About");
        bg.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Input Cost");
        bg.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 198, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setText("Sales Report");
        bg.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("Employees");
        bg.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setText("Food's Menu");
        bg.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 540));

        menupanal1.setBackground(new java.awt.Color(255, 255, 255));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu ID", "Name", "Previous Price", "Offer Price"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        menutable1.setViewportView(tbl);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Item Name      :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Previous Price  :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Offer Price        :");

        oname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        oprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oprice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        fprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fprice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout menupanal1Layout = new javax.swing.GroupLayout(menupanal1);
        menupanal1.setLayout(menupanal1Layout);
        menupanal1Layout.setHorizontalGroup(
            menupanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menupanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menutable1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menupanal1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(menupanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menupanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menupanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(oname, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(oprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        menupanal1Layout.setVerticalGroup(
            menupanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menutable1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menupanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(oname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menupanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(oprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menupanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fprice))
                .addGap(18, 18, 18))
        );

        jPanel1.add(menupanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 400, 480));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("( Exclusive Offer )");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu List");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Order Details");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        next.setBackground(new java.awt.Color(102, 102, 0));
        next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 204));
        next.setText("Next   >>");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 290, 30));

        orderpanal.setBackground(new java.awt.Color(255, 255, 255));

        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price (Total)"
            }
        ));
        ordertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordertableMouseClicked(evt);
            }
        });
        menutable.setViewportView(ordertable);

        add.setBackground(new java.awt.Color(0, 102, 0));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(204, 255, 204));
        add.setText(" Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delet.setBackground(new java.awt.Color(153, 0, 0));
        delet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delet.setForeground(new java.awt.Color(255, 204, 204));
        delet.setText("Remove");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Placement :");

        placement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        placement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Table - 1", "Table - 2", "Table - 3", "Table - 4", "Table - 5", "Table - 6", "Table - 7", "Table - 8", "Parcel" }));

        qnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantity    :");

        ttl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ttl.setForeground(new java.awt.Color(255, 255, 255));
        ttl.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Charges : ");

        javax.swing.GroupLayout orderpanalLayout = new javax.swing.GroupLayout(orderpanal);
        orderpanal.setLayout(orderpanalLayout);
        orderpanalLayout.setHorizontalGroup(
            orderpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderpanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderpanalLayout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(menutable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(orderpanalLayout.createSequentialGroup()
                        .addGroup(orderpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(orderpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qnt)
                            .addComponent(placement, 0, 185, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderpanalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        orderpanalLayout.setVerticalGroup(
            orderpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderpanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menutable, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttl)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(orderpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(orderpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(placement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(orderpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jPanel1.add(orderpanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 290, 480));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AfterLogin - Copy.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1210, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel7MouseClicked

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:

        int i = tbl.getSelectedRow();
        TableModel model = tbl.getModel();

        mnname = model.getValueAt(i, 1).toString();
        String pr = model.getValueAt(i, 3).toString();
        prprice = Integer.parseInt(pr);

        oname.setText(model.getValueAt(i, 1).toString());
        oprice.setText(model.getValueAt(i, 2).toString() + " TK.");
        fprice.setText(model.getValueAt(i, 3).toString() + " TK.");


    }//GEN-LAST:event_tblMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String REGEX = "[a-zA-Z]+$";
        if (qnt.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Provide the Quantity.", "Need!", 2);
        } else if (qnt.getText().matches(REGEX)) {
            JOptionPane.showMessageDialog(null, "Input numerical digit.", "Need!", 2);
        } else {
            String qntt = qnt.getText();
            int qnttt = Integer.parseInt(qntt);
            int prices = prprice * qnttt;
            String place = placement.getSelectedItem().toString();
            try {

                String query1 = "UPDATE `employee` SET `FoodServe`=`FoodServe`+? WHERE `Placement`= '" + place + "';";
                PreparedStatement ps1 = con.prepareStatement(query1);
                ps1.setInt(1, prices);
                ps1.executeUpdate();

                Statement stm = con.createStatement();
                String query = " insert into `order`(Date,Time,name, quantity, Price,Placement)" + " values(DATE_FORMAT(NOW(),'%Y-%m-%d'),DATE_FORMAT(NOW(),'%h:%i %p'),?,?,?,?);";
                PreparedStatement ps = con.prepareStatement(query);
//                ps.setString(1, prid);
//                ps.setString(1, date);
                ps.setString(1, mnname);
                ps.setInt(2, qnttt);
                ps.setInt(3, prices);
                ps.setString(4, place);

                ps.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) ordertable.getModel();
                model.setRowCount(0);
                show_order();

                String totalcrg = "SELECT SUM(Price) FROM `order`;";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(totalcrg);
                while (rs.next()) {
                    String prc = rs.getString("SUM(Price)");
                    ttl.setText(prc + " TK.");
                }

//                qnt.setText("");
//                JOptionPane.showMessageDialog(null, "Successfully Submitted ! ", "Welcome!", 1);
            } catch (HeadlessException | SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed
        // TODO add your handling code here:
        int prices = 0;
        String place = "";
        int row = ordertable.getSelectedRow();
        String value = (ordertable.getModel().getValueAt(row, 0).toString());
        try {

            String ppl = "SELECT `Price`,`Placement` FROM `order` WHERE `name` = '" + value + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(ppl);
            while (rs.next()) {
                prices = rs.getInt("Price");
                place = rs.getString("Placement");
            }

            String query1 = "UPDATE `employee` SET `FoodServe`=`FoodServe`-? WHERE `Placement`= '" + place + "';";
            PreparedStatement ps1 = con.prepareStatement(query1);
            ps1.setInt(1, prices);
            ps1.executeUpdate();

            String query = "DELETE FROM `order` WHERE `name` = '" + value + "'";

            PreparedStatement ps = con.prepareStatement(query);

            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) ordertable.getModel();
            model.setRowCount(0);
            show_order();

            String totalcrg = "SELECT SUM(Price) FROM `order`;";
            st = con.createStatement();
            rs = st.executeQuery(totalcrg);
            while (rs.next()) {
                String prc = rs.getString("SUM(Price)");
                ttl.setText(prc + " TK.");
            }

//            qnt.setText("");
//                JOptionPane.showMessageDialog(null, "Successfully Deleted ! ", "Welcome!", 1);
        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_deletActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:

        OrderManagements lg = new OrderManagements();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();

    }//GEN-LAST:event_nextActionPerformed

    private void ordertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordertableMouseClicked
        // TODO add your handling code here:
        int i = ordertable.getSelectedRow();
        TableModel model = ordertable.getModel();

    }//GEN-LAST:event_ordertableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerOffer sb = new CustomerOffer();
//                sb.dispose();
//                sb.setTitle("Rakib's Restaurant Management System");
                sb.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton add;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cust;
    private javax.swing.JToggleButton delet;
    private javax.swing.JLabel fprice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel menubar;
    private javax.swing.JPanel menupanal1;
    private javax.swing.JScrollPane menutable;
    private javax.swing.JScrollPane menutable1;
    private javax.swing.JToggleButton next;
    private javax.swing.JLabel oname;
    private javax.swing.JLabel oprice;
    private javax.swing.JPanel orderpanal;
    private javax.swing.JTable ordertable;
    private javax.swing.JComboBox<String> placement;
    private javax.swing.JTextField qnt;
    private javax.swing.JTable tbl;
    private javax.swing.JLabel ttl;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel urestu;
    // End of variables declaration//GEN-END:variables
}
