
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MD RAKIBUL ISLAM
 */
public class Employees extends javax.swing.JFrame {

    public ImageIcon icn;
    Connection con = null;
    String menutype = "SELECT * FROM employee";

    /**
     * Creates new form SetImageBackground
     */
    public Employees() {
        con = DB.dbconnect();
//        this.setUndecorated(true);
//        this.setAlwaysOnTop(true);
        this.setTitle("Restaurant RRMS");

        icn = new ImageIcon(getClass().getResource("/Images/icn.png"));
        this.setIconImage(icn.getImage());
        this.setResizable(false);
        initComponents();
        show_menu();
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        bg.setBackground(new Color(0, 0, 0, 200));
        menubar.setBackground(new Color(0, 0, 0, 200));
        menupanal.setBackground(new Color(0, 0, 0, 150));
        Login lg = new Login();
        uname.setText(lg.user);
        urestu.setText(lg.restu);
    }

    public ArrayList<Menus> menuList() {
        ArrayList<Menus> menuList = new ArrayList<>();
        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant", "root", "");
//            System.out.println("Connecteced !!");
            String queryl = menutype;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(queryl);
            Menus menu;
            while (rs.next()) {
                menu = new Menus(rs.getString("Staff_ID"), rs.getString("Name"), rs.getString("Designation"), rs.getString("Placement"),rs.getString("FoodServe"), rs.getString("Salary"));
                menuList.add(menu);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return menuList;
    }

    public void show_menu() {
        ArrayList<Menus> list = menuList();
        DefaultTableModel model = (DefaultTableModel) employeetable.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getDate();
            row[1] = list.get(i).getTime();
            row[2] = list.get(i).getName();
            row[3] = list.get(i).getQuantity();
            row[4] = list.get(i).getPrice();
            row[5] = list.get(i).getPlacement();
            model.addRow(row);
        }
    }

    public ArrayList<orders> orderList() {
        ArrayList<orders> orderList = new ArrayList<>();
        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant", "root", "");
//            System.out.println("Connecteced !!");
//            String queryl = menutype;
            String queryl = menutype;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(queryl);
            orders order;
            while (rs.next()) {
                order = new orders(rs.getString("Placement"), rs.getString("Name"), rs.getString("TotalServe"));
                orderList.add(order);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return orderList;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menubar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edit = new javax.swing.JToggleButton();
        add = new javax.swing.JToggleButton();
        delete = new javax.swing.JToggleButton();
        bg = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        urestu = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menupanal = new javax.swing.JPanel();
        menutable = new javax.swing.JScrollPane();
        employeetable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mnprice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mntype = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        slry = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        place = new javax.swing.JComboBox<>();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RAKIB'S RESTAURANT MANAGEMENT SYSTEM");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Setting |");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Log Out");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icn36.png"))); // NOI18N

        javax.swing.GroupLayout menubarLayout = new javax.swing.GroupLayout(menubar);
        menubar.setLayout(menubarLayout);
        menubarLayout.setHorizontalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        menubarLayout.setVerticalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(menubarLayout.createSequentialGroup()
                        .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        edit.setBackground(new java.awt.Color(102, 102, 0));
        edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 204));
        edit.setText("Edit Staff");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 150, -1));

        add.setBackground(new java.awt.Color(0, 102, 51));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(204, 255, 204));
        add.setText("Add New Staff");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 140, -1));

        delete.setBackground(new java.awt.Color(153, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 204, 204));
        delete.setText("Delete Staff");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 150, -1));

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 255, 153));
        jLabel20.setText("Welcome !");
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 438, -1, -1));

        uname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uname.setForeground(new java.awt.Color(102, 255, 255));
        uname.setText("Mr. User");
        bg.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 461, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 255, 255));
        jLabel22.setText("(Manager)");
        bg.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 484, -1, 15));

        urestu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        urestu.setForeground(new java.awt.Color(102, 255, 255));
        urestu.setText("ABC RESTAURANT");
        bg.add(urestu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 505, -1, 15));

        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 419, 250, 13));

        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 250, 12));

        jSeparator5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 210, 260, 12));

        jSeparator6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 240, 12));

        jSeparator7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 350, 260, 12));

        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 260, 12));

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 0));
        jLabel19.setText("Order Now");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(28, 28, 28))
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 50));

        jSeparator8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 10));

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 0));
        jLabel21.setText("Input Cost");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 50));

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 0));
        jLabel24.setText("About");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addContainerGap())
        );

        bg.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, 50));

        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 0));
        jLabel29.setText("Sales Report");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addContainerGap())
        );

        bg.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 210, 50));

        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 0));
        jLabel30.setText("Food's Menu");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );

        bg.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 50));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 51));
        jLabel25.setText("Employees");
        bg.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 540));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee List :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        menupanal.setBackground(new java.awt.Color(255, 255, 255));

        employeetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff  ID", "Name", "Designation", "Placement", "Food Serve(BDT)", "Salary(BDT)"
            }
        ));
        employeetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeetableMouseClicked(evt);
            }
        });
        menutable.setViewportView(employeetable);
        if (employeetable.getColumnModel().getColumnCount() > 0) {
            employeetable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Placement :");

        mnprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Designation :");

        mntype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mntype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Waiter", "Cleaner", "Chef" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Salary :");

        slry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Manage Employee :");

        place.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        place.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Table - 1", "Table - 2", "Table - 3", "Table - 4", "Table - 5", "Table - 6", "Table - 7", "Table - 8", "Kitchen", "No need" }));

        javax.swing.GroupLayout menupanalLayout = new javax.swing.GroupLayout(menupanal);
        menupanal.setLayout(menupanalLayout);
        menupanalLayout.setHorizontalGroup(
            menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menutable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menupanalLayout.createSequentialGroup()
                        .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mnprice, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(place, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(92, 92, 92)
                        .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mntype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(slry)))
                    .addComponent(jSeparator11)
                    .addComponent(jLabel10)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        menupanalLayout.setVerticalGroup(
            menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menutable, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menupanalLayout.createSequentialGroup()
                        .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(mnprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(menupanalLayout.createSequentialGroup()
                            .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(mntype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(menupanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(slry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel1.add(menupanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 710, 520));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AfterLogin - Copy.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1210, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Setting lg = new Setting();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        AdminShowMenu lg = new AdminShowMenu();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        AdminOrderManagement lg = new AdminOrderManagement();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        InputCost lg = new InputCost();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        SalesReport lg = new SalesReport();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        CAbout lg = new CAbout();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        AdminOrderManagement lg = new AdminOrderManagement();
        lg.setVisible(true);
        this.dispatchEvent(new WindowEvent(
                this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void employeetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeetableMouseClicked
        // TODO add your handling code here:
        int i = employeetable.getSelectedRow();
        TableModel model = employeetable.getModel();

        mnprice.setText(model.getValueAt(i, 1).toString());
        slry.setText(model.getValueAt(i, 5).toString());
        String type1 = model.getValueAt(i, 2).toString();
        switch (type1) {
            case "Waiter":
                mntype.setSelectedIndex(0);
                break;
            case "Cleaner":
                mntype.setSelectedIndex(1);
                break;
            case "Chef":
                mntype.setSelectedIndex(2);
                break;
        }
        String type2 = model.getValueAt(i, 3).toString();
        switch (type2) {
            case "Table - 1":
                place.setSelectedIndex(0);
                break;
            case "Table - 2":
                place.setSelectedIndex(1);
                break;
            case "Table - 3":
                place.setSelectedIndex(2);
                break;
            case "Table - 4":
                place.setSelectedIndex(3);
                break;
            case "Table - 5":
                place.setSelectedIndex(4);
                break;
            case "Table - 6":
                place.setSelectedIndex(5);
                break;
            case "Table - 7":
                place.setSelectedIndex(6);
                break;
            case "Table - 8":
                place.setSelectedIndex(7);
                break;
            case "Kitchen":
                place.setSelectedIndex(8);
                break;
            case "No need":
                place.setSelectedIndex(9);
                break;
        }
    }//GEN-LAST:event_employeetableMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if (mnprice.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Provide the Name.", "Need!", 2);
        } else if (slry.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Provide the Salary.", "Need!", 2);
        } else {
//            String prid = mnid.getText().toUpperCase();
            String prname = place.getSelectedItem().toString();
            String prgen = mnprice.getText().toUpperCase();
            String sl = slry.getText().toUpperCase();
            String prcom = mntype.getSelectedItem().toString();
            try {
//                System.out.println("Database is connecting....");
                //                Class.forName("com.mysql.jdbc.Driver");
//                Class.forName("com.mysql.cj.jdbc.Driver");
//                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant", "root", "");
//                System.out.println("Connecteced !!");
                Statement stm = con.createStatement();

                String query = " insert into employee(Name,Designation ,Placement , Salary)" + " values(?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(query);

                ps.setString(1, prgen);
                ps.setString(2, prcom);
                ps.setString(3, prname);
                ps.setString(4, sl);

                ps.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) employeetable.getModel();
                model.setRowCount(0);
                show_menu();

//                JOptionPane.showMessageDialog(null, "Successfully Submitted ! ", "Welcome!", 1);
            } catch (HeadlessException | SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Successfully Updated ! ", "Welcome!", 1);
        if (mnprice.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Provide the Name.", "Need!", 2);
        } else if (slry.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Provide the Salary.", "Need!", 2);
        } else {
//            String prid = mnid.getText().toUpperCase();
            String prname = place.getSelectedItem().toString();
            String prgen = mnprice.getText().toUpperCase();
            String sl = slry.getText().toUpperCase();
            String prcom = mntype.getSelectedItem().toString();
            try {
//                System.out.println("Database is connecting....");
                //                Class.forName("com.mysql.jdbc.Driver");
//                Class.forName("com.mysql.cj.jdbc.Driver");
//                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant", "root", "");
//                System.out.println("Connecteced !!");
                Statement stm = con.createStatement();

                int row = employeetable.getSelectedRow();
                String value = (employeetable.getModel().getValueAt(row, 0).toString());
                String query = "UPDATE employee SET Name=?, Designation=?,Placement=?, Salary=? where `Staff_ID` = '" + value + "'";

                PreparedStatement ps = con.prepareStatement(query);

                ps.setString(1, prgen);
                ps.setString(2, prcom);
                ps.setString(3, prname);
                ps.setString(4, sl);

                ps.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) employeetable.getModel();
                model.setRowCount(0);
                show_menu();

//                JOptionPane.showMessageDialog(null, "Successfully Submitted ! ", "Welcome!", 1);
            } catch (Exception e) {

            }
        }

    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String prname = place.getSelectedItem().toString();
        String prgen = mnprice.getText().toUpperCase();
        String sl = slry.getText().toUpperCase();
        String prcom = mntype.getSelectedItem().toString();

        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Delete \" " + prgen + " \" ?", "Delete", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            try {
//                System.out.println("Database is connecting....");
                //                Class.forName("com.mysql.jdbc.Driver");
//                Class.forName("com.mysql.cj.jdbc.Driver");
//                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant", "root", "");
//                System.out.println("Connecteced !!");
                Statement stm = con.createStatement();

                int row = employeetable.getSelectedRow();
                String value = (employeetable.getModel().getValueAt(row, 0).toString());
                String query = "DELETE FROM `employee` WHERE `Staff_ID` = " + value;

                PreparedStatement ps = con.prepareStatement(query);

                ps.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) employeetable.getModel();
                model.setRowCount(0);
                show_menu();

//                JOptionPane.showMessageDialog(null, "Successfully Submitted ! ", "Welcome!", 1);
            } catch (HeadlessException | SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Employees sb = new Employees();
//                sb.dispose();
//                sb.setTitle("Rakib's Restaurant Management System");
                sb.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton add;
    private javax.swing.JPanel bg;
    private javax.swing.JToggleButton delete;
    private javax.swing.JToggleButton edit;
    private javax.swing.JTable employeetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel menubar;
    private javax.swing.JPanel menupanal;
    private javax.swing.JScrollPane menutable;
    private javax.swing.JTextField mnprice;
    private javax.swing.JComboBox<String> mntype;
    private javax.swing.JComboBox<String> place;
    private javax.swing.JTextField slry;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel urestu;
    // End of variables declaration//GEN-END:variables
}
